import { PathTemplate, Difficulty } from '@prisma/client';

export const pathTemplates: Omit<PathTemplate, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Beginner Friendly 4-Week',
    description: 'Perfect for beginners starting their interview preparation journey. Covers fundamental concepts with a gentle learning curve.',
    emoji: '🌱',
    durationWeeks: 4,
    difficulty: Difficulty.BEGINNER,
    targetAudience: 'Beginners',
    rules: {
      balanceTheoryPractice: true,
      maxDifficultyPerWeek: 'EASY',
      includeReviews: false,
      adaptiveDifficulty: true,
    } as any,
    includeModules: ['JavaScript Fundamentals'],
    excludeModules: [],
    minDifficulty: Difficulty.BEGINNER,
    maxDifficulty: Difficulty.EASY,
    lessonsPerDay: 2,
    daysPerWeek: 5,
    estimatedHoursPerDay: 2.0,
    isActive: true,
  },
  {
    name: 'Comprehensive 12-Week',
    description: 'Complete interview preparation covering all modules. Ideal for thorough preparation over 3 months.',
    emoji: '🚀',
    durationWeeks: 12,
    difficulty: Difficulty.MEDIUM,
    targetAudience: 'Intermediate to Advanced',
    rules: {
      balanceTheoryPractice: true,
      includeReviews: true,
      adaptiveDifficulty: true,
      weeklyAssessments: true,
      companySpecificFocus: false,
    } as any,
    includeModules: [],
    excludeModules: [],
    minDifficulty: Difficulty.EASY,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 3,
    daysPerWeek: 6,
    estimatedHoursPerDay: 3.0,
    isActive: true,
  },
  {
    name: 'Fast-Track 8-Week',
    description: 'Accelerated learning path for those with some experience. Intensive schedule with advanced topics.',
    emoji: '⚡',
    durationWeeks: 8,
    difficulty: Difficulty.MEDIUM,
    targetAudience: 'Experienced Developers',
    rules: {
      balanceTheoryPractice: false, // More practice focused
      includeReviews: true,
      adaptiveDifficulty: false,
      weeklyAssessments: true,
      priorityToAdvanced: true,
    } as any,
    includeModules: [],
    excludeModules: ['JavaScript Fundamentals'], // Skip basics
    minDifficulty: Difficulty.EASY,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 4,
    daysPerWeek: 6,
    estimatedHoursPerDay: 4.0,
    isActive: true,
  },
  {
    name: 'Google Focus 10-Week',
    description: 'Specialized preparation for Google interviews with emphasis on algorithms, system design, and behavioral rounds.',
    emoji: '🎯',
    durationWeeks: 10,
    difficulty: Difficulty.HARD,
    targetAudience: 'Google Applicants',
    rules: {
      balanceTheoryPractice: true,
      includeReviews: true,
      adaptiveDifficulty: true,
      weeklyAssessments: true,
      companySpecificFocus: true,
      targetCompanies: ['Google'],
      emphasizeSystemDesign: true,
      emphasizeAlgorithms: true,
    } as any,
    includeModules: [],
    excludeModules: [],
    minDifficulty: Difficulty.MEDIUM,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 3,
    daysPerWeek: 6,
    estimatedHoursPerDay: 3.5,
    isActive: true,
  },
  {
    name: 'FAANG Focus 16-Week',
    description: 'Comprehensive preparation for FAANG interviews with deep coverage of all topics and mock interviews.',
    emoji: '🏆',
    durationWeeks: 16,
    difficulty: Difficulty.HARD,
    targetAudience: 'FAANG Applicants',
    rules: {
      balanceTheoryPractice: true,
      includeReviews: true,
      adaptiveDifficulty: true,
      weeklyAssessments: true,
      companySpecificFocus: true,
      targetCompanies: ['Facebook', 'Amazon', 'Apple', 'Netflix', 'Google'],
      emphasizeSystemDesign: true,
      emphasizeAlgorithms: true,
      includeMockInterviews: true,
      behavioralTraining: true,
    } as any,
    includeModules: [],
    excludeModules: [],
    minDifficulty: Difficulty.MEDIUM,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 3,
    daysPerWeek: 5,
    estimatedHoursPerDay: 3.0,
    isActive: true,
  },
  {
    name: 'Weekend Warrior 6-Week',
    description: 'Designed for working professionals - intensive weekend sessions with lighter weekday practice.',
    emoji: '📅',
    durationWeeks: 6,
    difficulty: Difficulty.MEDIUM,
    targetAudience: 'Working Professionals',
    rules: {
      balanceTheoryPractice: true,
      includeReviews: false,
      adaptiveDifficulty: true,
      weekendIntensive: true,
      weekdayLight: true,
    } as any,
    includeModules: [],
    excludeModules: [],
    minDifficulty: Difficulty.EASY,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 2,
    daysPerWeek: 3, // Friday evening + Saturday + Sunday
    estimatedHoursPerDay: 4.0,
    isActive: true,
  },
  {
    name: 'DSA Deep Dive 6-Week',
    description: 'Focused on Data Structures and Algorithms for those who want to master problem-solving.',
    emoji: '🧮',
    durationWeeks: 6,
    difficulty: Difficulty.MEDIUM,
    targetAudience: 'DSA Enthusiasts',
    rules: {
      balanceTheoryPractice: false,
      includeReviews: true,
      adaptiveDifficulty: true,
      emphasisOnPractice: true,
      dailyCodingChallenge: true,
    } as any,
    includeModules: ['DSA Fundamentals'],
    excludeModules: ['System Design', 'Behavioral', 'Machine Coding'],
    minDifficulty: Difficulty.EASY,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 4,
    daysPerWeek: 6,
    estimatedHoursPerDay: 3.0,
    isActive: true,
  },
  {
    name: 'System Design Masterclass 4-Week',
    description: 'Intensive system design preparation covering architecture, scaling, and distributed systems.',
    emoji: '🏗️',
    durationWeeks: 4,
    difficulty: Difficulty.HARD,
    targetAudience: 'System Design Candidates',
    rules: {
      balanceTheoryPractice: true,
      includeReviews: true,
      adaptiveDifficulty: false,
      emphasizeSystemDesign: true,
      includeRealWorldExamples: true,
      caseStudyBased: true,
    } as any,
    includeModules: ['System Design'],
    excludeModules: [],
    minDifficulty: Difficulty.MEDIUM,
    maxDifficulty: Difficulty.HARD,
    lessonsPerDay: 2,
    daysPerWeek: 5,
    estimatedHoursPerDay: 2.5,
    isActive: true,
  },
];
